import Head from 'next/head'
import styles from '@component/styles/Home.module.css'
import Dashboard from './dashboard/Dashboard'
import Login from '@component/component/login/Login'
import Header from '@component/component/Header'
import SideMenu from '@component/component/SideMenu'
export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Header/>
        <SideMenu/>
        <Dashboard/>
        <Login/>
      </main>
    </>
  )
}
