import Head from 'next/head'
import Dashboard from './dashboard/Dashboard'
import Login from '@component/component/login/Login'
import Header from '@component/component/Header'
import SideMenu from '@component/component/SideMenu'
import { useSession } from 'next-auth/react'
import darkTheme from '@component/theme/darkTheme'
import scss from "../styles/Home.module.scss"
const Home: React.FunctionComponent = function () {
  const { data: session } = useSession()
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={scss.main}>
        <Header />
        {
          session && (
            <>
              <SideMenu />
              <Dashboard />
            </>
          )
        }
        <Login />
      </main>
    </>
  )
}
export default Home;